services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=mijn_wachtwoord
    command: "start-notebook.sh --NotebookApp.ip=0.0.0.0 --NotebookApp.allow_origin='*'"
   